### ISSUE TITLE
Debug via containerized toolchain & DAP server

### ISSUE THREAD

**Issue by sfavazza** [emacs-lsp/dap-mode#816]
The setup I am working on features the entire toolchain in a container (both GDB & GDB-server).
I wonder whether it is possible to configure a debug session via `launch.json` file such that dap-mode execute the debugger from within the docker container.

In particular I have difficulties to understand the 2 keywords **provider** and **template** of the `.lsp-docker` configuration file.

Should these files be visible in the container? Do you have an example?

Assuming the `.lsp-docker` part is properly configured, shall I indicate docker-paths in the `launch.json` keywords `miDebuggerPath` and `debugServerPath`?

**Comment by sfavazza** [comment]
Based on my investigation it seems that **provider** and (optional) **template** must already exist, such that the `dap-docker-register` will append the `Dockerized` word to both the newly created provider and template.

E.g. assuming I want to run a GDB session in a container I will have:
```yaml
lsp:
  server:
    mappings:
    - source: .
      destination: /code
   debug:
      type: docker
      subtype: container
      name: <my-dap-container-name>
      enabled: true
      provider: "cppdbg"
      template: "cpptools::Run Configuration"
      launch_command: "/inside-docker/path/to/debugger"
```
This in turn creates:
- dockerized provider named: `abs-path-to-project-cppdbgDocker`
- dockerized template: `cpptools::Run Configuration Dockerized`

Hence to start a debugging session the `launch.json` file would look like this:

```json
{
    "configurations": [
        {
            "name": "DAP C/C++ (dockerized)",
            "type": "abs-path-to-project-cppdbgDocker",
            "request": "launch",
            "MIMode": "gdb",
            "miDebuggerServerAddress": ":${env:TARGET_DBG_PORT}",
            // container local paths
            "miDebuggerPath": "/inside/docker/path/to/gdb",
            "miDebuggerArgs": "-x /code/.vscode/.gdbinit",
            "program": "<my-program-abs-path>",
            "cwd": "${workspaceFolder}",
            // launch the debug server connecting to the target
            "debugServerPath": "/inside/docker/path/gdb-server",
        },
    ]
}
```

Is this the intended usage? Did I miss anything?

I found a caveat with the vscode-cpptools DAP server. When starting a debug session with the newly registered provider, the GDB-DAP-server expects to find a `*.ad7Engine.json` file where the `*` is the value of the `launch.json` key:
- Is this expected?
- Does anyone bumped into the same issue with other DAP servers?
